
import { useState } from "react";
import { Link } from "react-router-dom";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import { ZenoraButton } from "@/components/ui/button-zenora";
import { HelpCircle, Mail, MessageSquare, Phone } from "lucide-react";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";

const Help = () => {
  const [activeTab, setActiveTab] = useState<"faq" | "contact" | "support">("faq");

  const faqs = [
    {
      question: "How do I add a new property to my dashboard?",
      answer: "To add a new property, navigate to the My Properties section and click the 'Add Property' button. Fill in the property details form and submit. Your new property will appear in your dashboard immediately."
    },
    {
      question: "How accurate is the AI Rent Analysis?",
      answer: "Our AI Rent Analysis uses advanced algorithms and local market data to provide estimates with approximately 95% accuracy. The analysis is based on comparable properties, market trends, and specific property details you provide."
    },
    {
      question: "Can I export the reports generated by Zenora?",
      answer: "Yes! All reports generated through our platform can be exported as PDF or CSV files. Simply navigate to the Reports section, find the report you want to export, and click the download icon in the top right corner."
    },
    {
      question: "How do I upgrade my subscription plan?",
      answer: "You can upgrade your plan by clicking on the 'Upgrade' button in your dashboard sidebar. You'll be presented with available plans and payment options. Changes to your subscription take effect immediately after payment processing."
    },
    {
      question: "Is my data secure on Zenora?",
      answer: "Absolutely. We employ industry-standard encryption and security protocols to protect your data. All information is stored in secure cloud environments with regular backups. We never share your personal information with third parties without your explicit consent."
    }
  ];

  const renderContent = () => {
    switch (activeTab) {
      case "contact":
        return (
          <div className="space-y-6">
            <h2 className="text-2xl font-bold mb-6">Contact Our Team</h2>
            <p className="text-muted-foreground mb-6">
              Our customer support team is available Monday through Friday, 9AM to 5PM PT.
            </p>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
              <div className="zenora-card p-6">
                <div className="rounded-full bg-zenora-purple/10 w-12 h-12 flex items-center justify-center mb-4">
                  <Phone className="h-6 w-6 text-zenora-purple" />
                </div>
                <h3 className="text-lg font-semibold mb-2">Call Us</h3>
                <p className="text-muted-foreground mb-4">Speak directly with our support team</p>
                <p className="font-medium">(555) 123-4567</p>
              </div>

              <div className="zenora-card p-6">
                <div className="rounded-full bg-zenora-purple/10 w-12 h-12 flex items-center justify-center mb-4">
                  <Mail className="h-6 w-6 text-zenora-purple" />
                </div>
                <h3 className="text-lg font-semibold mb-2">Email Us</h3>
                <p className="text-muted-foreground mb-4">Get a response within 24 hours</p>
                <p className="font-medium">support@zenora.com</p>
              </div>

              <div className="zenora-card p-6">
                <div className="rounded-full bg-zenora-purple/10 w-12 h-12 flex items-center justify-center mb-4">
                  <MessageSquare className="h-6 w-6 text-zenora-purple" />
                </div>
                <h3 className="text-lg font-semibold mb-2">Live Chat</h3>
                <p className="text-muted-foreground mb-4">Chat with our support agents</p>
                <ZenoraButton className="w-full">Start Chat</ZenoraButton>
              </div>
            </div>
          </div>
        );
      case "support":
        return (
          <div className="space-y-6">
            <h2 className="text-2xl font-bold mb-6">Submit a Support Ticket</h2>
            <p className="text-muted-foreground mb-6">
              Need more detailed help? Submit a support ticket and our team will respond as soon as possible.
            </p>

            <div className="zenora-card p-6">
              <form className="space-y-4">
                <div>
                  <label htmlFor="name" className="block text-sm font-medium mb-1">Full Name</label>
                  <input id="name" type="text" className="zenora-input" placeholder="John Doe" />
                </div>
                
                <div>
                  <label htmlFor="email" className="block text-sm font-medium mb-1">Email Address</label>
                  <input id="email" type="email" className="zenora-input" placeholder="john@example.com" />
                </div>
                
                <div>
                  <label htmlFor="issue" className="block text-sm font-medium mb-1">Issue Category</label>
                  <select id="issue" className="zenora-input">
                    <option value="">Select an issue category</option>
                    <option value="account">Account Access</option>
                    <option value="billing">Billing & Subscription</option>
                    <option value="properties">Property Management</option>
                    <option value="reports">Reports & Analysis</option>
                    <option value="other">Other</option>
                  </select>
                </div>
                
                <div>
                  <label htmlFor="description" className="block text-sm font-medium mb-1">Describe Your Issue</label>
                  <textarea id="description" className="zenora-input min-h-[120px]" placeholder="Please provide as much detail as possible..."></textarea>
                </div>
                
                <div>
                  <label className="flex items-center">
                    <input type="checkbox" className="mr-2" />
                    <span className="text-sm">I agree to be contacted via email about this issue</span>
                  </label>
                </div>
                
                <ZenoraButton type="submit" className="w-full">Submit Support Ticket</ZenoraButton>
              </form>
            </div>
          </div>
        );
      case "faq":
      default:
        return (
          <div className="space-y-6">
            <h2 className="text-2xl font-bold mb-6">Frequently Asked Questions</h2>
            
            <Accordion type="single" collapsible className="zenora-card">
              {faqs.map((faq, index) => (
                <AccordionItem key={index} value={`item-${index}`}>
                  <AccordionTrigger className="px-4 text-left hover:no-underline">
                    {faq.question}
                  </AccordionTrigger>
                  <AccordionContent className="px-4 pb-4">
                    {faq.answer}
                  </AccordionContent>
                </AccordionItem>
              ))}
            </Accordion>
            
            <div className="text-center p-6 zenora-card bg-zenora-purple/5">
              <HelpCircle className="h-12 w-12 mx-auto text-zenora-purple mb-4" />
              <h3 className="text-xl font-semibold mb-2">Still have questions?</h3>
              <p className="text-muted-foreground mb-4">
                Our team is here to help you with any questions or concerns.
              </p>
              <div className="flex flex-col sm:flex-row gap-2 justify-center">
                <ZenoraButton 
                  variant="outline" 
                  onClick={() => setActiveTab("contact")}
                >
                  Contact Us
                </ZenoraButton>
                <ZenoraButton 
                  onClick={() => setActiveTab("support")}
                >
                  Submit a Ticket
                </ZenoraButton>
              </div>
            </div>
          </div>
        );
    }
  };

  return (
    <div className="min-h-screen flex flex-col">
      <Navbar />
      
      <main className="flex-grow py-16 bg-gradient-to-b from-white to-gray-50 dark:from-zenora-dark dark:to-black">
        <div className="zenora-container">
          <div className="text-center mb-12">
            <h1 className="text-3xl sm:text-4xl font-extrabold tracking-tight mb-4 bg-clip-text text-transparent bg-zenora-gradient">
              Help & Support
            </h1>
            <p className="text-muted-foreground max-w-xl mx-auto">
              Find answers to common questions or get in touch with our support team for personalized assistance.
            </p>
          </div>
          
          <div className="flex justify-center mb-8">
            <div className="inline-flex rounded-md shadow-sm">
              <button
                onClick={() => setActiveTab("faq")}
                className={`px-4 py-2 text-sm font-medium border rounded-l-md ${
                  activeTab === "faq"
                    ? "bg-zenora-gradient text-white border-zenora-purple"
                    : "bg-white dark:bg-zenora-dark border-gray-200 dark:border-gray-700 text-gray-700 dark:text-gray-300 hover:bg-gray-50 dark:hover:bg-gray-800"
                }`}
              >
                FAQ
              </button>
              <button
                onClick={() => setActiveTab("contact")}
                className={`px-4 py-2 text-sm font-medium border-t border-b ${
                  activeTab === "contact"
                    ? "bg-zenora-gradient text-white border-zenora-purple"
                    : "bg-white dark:bg-zenora-dark border-gray-200 dark:border-gray-700 text-gray-700 dark:text-gray-300 hover:bg-gray-50 dark:hover:bg-gray-800"
                }`}
              >
                Contact Us
              </button>
              <button
                onClick={() => setActiveTab("support")}
                className={`px-4 py-2 text-sm font-medium border rounded-r-md ${
                  activeTab === "support"
                    ? "bg-zenora-gradient text-white border-zenora-purple"
                    : "bg-white dark:bg-zenora-dark border-gray-200 dark:border-gray-700 text-gray-700 dark:text-gray-300 hover:bg-gray-50 dark:hover:bg-gray-800"
                }`}
              >
                Support Ticket
              </button>
            </div>
          </div>
          
          {renderContent()}
        </div>
      </main>
      
      <Footer />
    </div>
  );
};

export default Help;
